### PR TITLE
[14.0] Improvements setting brand_id via team_id

### PR DESCRIPTION
**Pull request by mt-software-de**
at onchange team only change brand_id if set in team
set brand_id from team at default_get

### CODE REVIEW

**Review by sbejaoui — CHANGES_REQUESTED** [review]
1. pre-commit is red.
2. please add unit test.

**Review by sbejaoui — APPROVED** [review]
LGTM, thanks

**Comment by mt-software-de** [comment]
@sbejaoui how this pr will be merged to branch 15.0?

**Comment by sbejaoui** [comment]
> @sbejaoui how this pr will be merged to branch 15.0?

we need a new pr for 15.0

**Comment by mt-software-de** [comment]
> > @sbejaoui how this pr will be merged to branch 15.0?
> 
> we need a new pr for 15.0

https://github.com/OCA/brand/pull/120

**Pull request merged**
