### PR TITLE
[12.0][REF] - Add new model res.brand for partner brand

### PR DESCRIPTION
**Pull request by sbejaoui**
This pull request add a dedicated object for brands.

### CODE REVIEW

**Comment by levkar** [comment]
why not have base_brand instead of partner_brand?

**Comment by max3903** [comment]
@sbejaoui Too many modules in the same pull request. My brain can't process... :) Can you split to have one module per pull request please?

**Comment by sbejaoui** [comment]
> @sbejaoui Too many modules in the same pull request. My brain can't process... :) Can you split to have one module per pull request please?

Hi @max3903 ,
Thank you for your comment.
I understand your concern. I removed the last commit that add new feature to the `account_brand` module.
The PR now treat the same subject which is adding a new model instead of using the `res.partner` to manage company brands.
Each commit concern one module at the time with its migration scripts. Maybe it's easier if you review one by one.
I prefer to keep them in the same PR as each module depends on the others so we can functionally test the refactoring.

**Review by max3903 — APPROVED** [review]
LGTM. Not tested yet.

**Comment by max3903** [comment]
@sbejaoui I tested the migration scripts and features. Everything works as expected. Great work. Thank you :+1:

**Comment by sbejaoui** [comment]
> @sbejaoui I tested the migration scripts and features. Everything works as expected. Great work. Thank you

Thank you @max3903 for you review. @gva-acsone made a functional test too. We wait his approve to merge this.

**Review by bodedra — APPROVED** [review]
@sbejaoui : Good job. LGTM :+1:  I have following one question.

Are we move `partner_brand` module from OCA/brand to OCA/partner-contact ? If no, then we have to revert back changes in readme folder.

**Comment by sbejaoui** [comment]
> @sbejaoui : Good job. LGTM  I have following one question.
> 
> Are we move `partner_brand` module from OCA/brand to OCA/partner-contact ? If no, then we have to revert back changes in readme folder.

Thank you for your review.

After merge, changes will be overwritten in the readme file and repository link and name will be fixed.

**Pull request merged**
