### PR TITLE
[FIX] brand view in analytic_brand

### PR DESCRIPTION
**Pull request by BT-tkarpinski**
analytic_account_id was outside form view

image

### CODE REVIEW

**Comment by BT-tkarpinski** [comment]
@BT-anieto @BT-jmichaud

**Comment by BT-jmichaud** [comment]
LGTM

**Review by BT-anieto — APPROVED** [review]
LGTM

**Review by BT-jmichaud — APPROVED** [review]

**Review by sbejaoui — APPROVED** [review]

**Pull request merged**
