### PR TITLE
product_brand: relicense AGPL -> LGPL

### PR DESCRIPTION
**Pull request by simahawk**
Now a "funny" story. To check which authors I had to ping to validate this change I checked the manifest and its history and I've seen quite some weird stuff. There you go:

1. The ownership was stolen here on mig to v8 https://github.com/OCA/product-attribute/commit/cfa8838925849183bbd0b50bc41029ea2228df61 by "Prisnet Telecommunications SA" setting themselves as the only authors. They shouldn't even been listed as an author because they did nothing beside moving the module from `__unported__` folder
3. this has been partially fixed here https://github.com/OCA/product-attribute/commit/5f47177089f9367a75950095040c7d38d5031f95 where authors became "NetAndCo, Akretion, Prisnet Telecommunications SA"

Then other "dubious" attributions done on bare migration here and there.

To me we should remove some people from there, but yeah... I'll let real authors complain if they'd like :stuck_out_tongue_winking_eye: 

@pedrobaeza @bguillot good for you?

### CODE REVIEW

**Comment by simahawk** [comment]
FTR moved to GH actions here https://github.com/OCA/brand/pull/117

**Comment by simahawk** [comment]
@pedrobaeza @hparfr @bguillot @sbejaoui gentle ping :)

**Comment by pedrobaeza** [comment]
I prefer to not relicense to LGPL and stay as AGPL.

**Comment by hparfr** [comment]
I don't have strong opinion about this.

**Comment by bguillot** [comment]
I'm fine with the changes.

**Comment by simahawk** [comment]
Thanks for your feedback. If there's no agreement I'll switch `storage_image_product_brand` to AGPL unless anyone else is against it.

**Comment by simahawk** [comment]
https://github.com/OCA/storage/pull/207

**Pull request closed without merging**
