### PR TITLE
[14.0][FIX] brand

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Review by sbejaoui — APPROVED** [review]

**Comment by patrickrwilson** [comment]
@Freni-OSI are you able to apply this fix in the same PR as @AmmarOfficewalaSerpentCS instead of having this separate PR? That way we can just have the single migrated PR and verify it's green before merging.

**Comment by Freni-OSI** [comment]
> @Freni-OSI are you able to apply this fix in the same PR as @AmmarOfficewalaSerpentCS instead of having this separate PR? That way we can just have the single migrated PR and verify it's green before merging.

This is an issue of a brand module and we faced it in the account_brand module. so we will rebase the account_brand branch after this merge. so it will fix Travis of account_brand

**Review by patrickrwilson — APPROVED** [review]
Works and LGTM

**Pull request merged**
