### PR TITLE
[16.0][FIX] product_brand: Error getting sale data when pos_sale module is …

### PR DESCRIPTION
**Pull request by eantones**
…installed

This solves the issue https://github.com/OCA/brand/issues/141

### CODE REVIEW

**Review by sbejaoui — APPROVED** [review]

**Review by sbejaoui — APPROVED** [review]

**Comment by eantones** [comment]
@sbejaoui it seems there was an error merging, I just rebased, can you please try to merge again. Thanks!!

**Comment by eantones** [comment]
Pre-commit is failing due to a problem with some library... it's not a legitimate pre-commit error

**Comment by pedrobaeza** [comment]
A gift to you: #156

When you see a weird problem, it would be something related to the tooling. Probably other has already faced it and came with the solution. This solution is put in the template that we maintain in https://github.com/OCA/oca-addons-repo-template/. And if not, you can notify there about the problem.

If solved in the template, you can do `pipx run copier -f update` in the repo to get the latest template and update the definition. Is what I have done in my PR.

**Comment by eantones** [comment]
Fixed! Thanks @pedrobaeza for the quick PR and for the info about the template :-))))

**Pull request merged**
