### PR TITLE
[12.0] - Add sale_brand module

### PR DESCRIPTION
**Pull request by sbejaoui**
This PR move the [sale_band](https://github.com/OCA/sale-workflow/tree/12.0/sale_brand) module from [sale-workflow](https://github.com/OCA/sale-workflow) repository.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I still insist in differentiating both brand approaches. What about sale_company_branding or sale_company_brand?

**Comment by sbidoul** [comment]
@pedrobaeza this PR is just for moving existing modules. I suggest we discuss a possible renaming in a separate issue.

**Comment by pedrobaeza** [comment]
But that would mean that this is merged with the wrong name

**Comment by max3903** [comment]
@pedrobaeza This module is used in production. I believe renaming a module requires a migration script which is not in the scope of this pull request.

**Comment by pedrobaeza** [comment]
OK, do what you think

**Pull request merged**
