### PR TITLE
15.0 improvements branduselevel

### PR DESCRIPTION
**Pull request by mt-software-de**
This is the pr for the 15.0 version
https://github.com/OCA/brand/pull/96

### CODE REVIEW

**Comment by sbejaoui** [comment]
squash commits please

**Comment by mt-software-de** [comment]
> squash commits please

done

**Comment by sbejaoui** [comment]
please change the commit and pr message according to the [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

**Comment by mt-software-de** [comment]
> please change the commit and pr message according to the [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

Is the commit Message now as you expected it?

**Comment by sbejaoui** [comment]
it should be something like this:

```
[IMP] - get default brand use level from company if it's possible 

get the brand_use_level if there is a default value for company_id
```

**Comment by mt-software-de** [comment]
@sbejaoui any News in this?

**Review by sbejaoui — APPROVED** [review]

**Pull request merged**
