### PR TITLE
[MIG] account_brand: Migration to 13.0

### PR DESCRIPTION
**Pull request by cubells**
Standard migration.

Depends on https://github.com/OCA/brand/pull/27

### CODE REVIEW

**Comment by sbejaoui** [comment]
Hi @cubells ,

thank you for your contribution.

#27 is merged, can you rebase this PR on 13.0

**Comment by hparfr** [comment]
I had a bug with current PR and contract PR https://github.com/OCA/contract/pull/533 with this line Form(): 
https://github.com/OCA/contract/blob/1fb4be6ef2a6a23c3a861715af2ecb8e899b679e/contract/models/contract.py#L321

The cause is brand_use_level (defined in a mixin here:
https://github.com/OCA/brand/blob/13.0/brand/models/res_brand_mixin.py#L24 ) is not present in the views.

I guess adding brand_use_level in the orders and invoices views is doable but not very clean. What are the other alternatives ?

Any ideas @cubells @pedrobaeza  @sbejaoui  ?

**Comment by pedrobaeza** [comment]
I don't see the relation and why it's a problem...

**Comment by hparfr** [comment]
It's a problem because both modules work alone but not together.

**Comment by pedrobaeza** [comment]
Yeah, but what I need is:

- Steps to reproduce the problem.
- The problem itself (stacktrace, etc).

**Comment by hparfr** [comment]
Of course :)

Setup:
- install brand from oca/brand 13.0
- install account_brand from cubells/brand 13.0-mig-account_brand
- install contract from tecnativa/brand 13.0-mig-contract

Create an invoice: it works.

Create a contract.contract, set up a product, a start date then click on "create  invoices" button.
You get : 
```py
  File "/odoo/links/contract/models/contract.py", line 454, in recurring_create_invoice
    invoice = self._recurring_create_invoice()
  File "/odoo/links/contract/models/contract.py", line 467, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/odoo/links/contract/models/contract.py", line 440, in _prepare_recurring_invoices_values
    invoice_vals, move_form = contract._prepare_invoice(date_ref)
  File "/odoo/links/contract/models/contract.py", line 324, in _prepare_invoice
    force_company=self.company_id.id, default_type=invoice_type
  File "/odoo/src/odoo/tests/common.py", line 1444, in __init__
    self._process_fvg(recordp, fvg)
  File "/odoo/src/odoo/tests/common.py", line 1530, in _process_fvg
    fvg['onchange'] = model._onchange_spec(fvg)
  File "/odoo/src/odoo/models.py", line 5934, in _onchange_spec
    process(etree.fromstring(view_info['arch']), view_info, '')
  File "/odoo/src/odoo/models.py", line 5930, in process
    process(child, info, prefix)
  File "/odoo/src/odoo/models.py", line 5930, in process
    process(child, info, prefix)
  File "/odoo/src/odoo/models.py", line 5930, in process
    process(child, info, prefix)
  [Previous line repeated 1 more time]
  File "/odoo/src/odoo/models.py", line 5926, in process
    for subinfo in info['fields'][name].get('views', {}).values():
KeyError: 'brand_use_level'
```

**Comment by sbejaoui** [comment]
Hi @hparfr ,

I created #45 to finish this migration. I close this PR and I will look into the issue you reported.

**Pull request closed without merging**
