### PR TITLE
[14.0][MIG] sale_brand

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by sbejaoui** [comment]
please rebase on 14.0

**Comment by Freni-OSI** [comment]
Needs Review. @patrickrwilson

**Review by sbejaoui — APPROVED** [review]
Code Review

**Comment by patrickrwilson** [comment]
@Freni-OSI I tried to test this in runbot but there were two issues...
1. I couldn't get to the sales quote to test without installing sale_management, perhaps that module should be in depends instead of sale? (unless there is another way to get to a sales order in community?)  
2. On the sale quote view, I don't see the brand field.

image

**Comment by sbejaoui** [comment]
> @Freni-OSI I tried to test this in runbot but there were two issues...
> 
> 1. I couldn't get to the sales quote to test without installing sale_management, perhaps that module should be in depends instead of sale? (unless there is another way to get to a sales order in community?)

The sale_management is a module on top of the sale module that add some enhancement and activate the root menu for sale orders. You can activate it manually from Settings/Config/User Interface/menu item. Technically this module need only the sale module.

> 2. On the sale quote view, I don't see the brand field.
> 

check the brand brand_use_level in settings, it should be rather optional or required so the brand be visible in the sale order

**Comment by patrickrwilson** [comment]
Yep, that was my issue @sbejaoui, enabling that setting worked for me, thanks, I'll review now.

**Review by patrickrwilson — APPROVED** [review]
Tested and worked, code looks good. LGTM

**Pull request merged**
