### PR TITLE
[FIX] Adding tags to unittests for account_brand and sale_brand

### PR DESCRIPTION
**Pull request by mt-software-de**
If you do
`odoo -i account_brand --stop-after-init --test-enable`
or
`odoo -i sale_brand --stop-after-init --test-enable`

The unittests for
account_brand:
TestAccountAnalyticMove.test_move_analytic_account_onchange_brand
TestAccountMove.test_on_change_partner_id
TestBrandMixin.test_default_get
TestBrandMixin.test_reverse_move

sale_brand:
TestSaleOrder.test_create_down_payment_invoice
TestSaleOrder.test_create_invoice

will fail because of missing account.journal entries.
This was already discussed here. https://github.com/OCA/contract/pull/876

### CODE REVIEW

**Comment by mt-software-de** [comment]
@sbejaoui are there any news on this topic?

**Comment by mt-software-de** [comment]
@rousseldenis or @jbaudoux could you maybe have a look?

**Review by jbaudoux — APPROVED** [review]

**Review by bosd — APPROVED** [review]
Code change review, LGTM 👍

**Comment by bosd** [comment]
@sbejaoui Can you merge this 🙏

**Comment by bosd** [comment]
> @sbejaoui Can you merge this 🙏

Is there another maintaner who can merge this?

**Pull request merged**
